### ISSUE TITLE
Escaped apostrophes in string

### ISSUE THREAD

**Issue by steveosoule** [mghweb/Miva-Template-Language#4]
The syntax highlighting doesn't recognize escaped apostrophes within a string.

This is a valid mvt:assignment
```
<mvt:assign name="g.foo" value="'This is foo\'s string'" />
```

But the color-highlighting changes
[![Preview](http://content.screencast.com/users/ssoule4309/folders/Jing/media/654bf60d-3202-4cc1-af89-f74603d084ab/2016-02-09_1434.png)](http://screencast.com/t/ouAHkZgw)

**Comment by mghweb** [comment]
Thanks for letting me know!

I have pushed the update (https://github.com/mghweb/Miva-Template-Language/releases/tag/1.5.3)
